// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcgmpwnaupxugwvfnyjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZ21wd25hdXB4dWd3dmZueWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzkyNDQsImV4cCI6MjA1MzE1NTI0NH0.MNTeA9NxBVcQ0-_cONvqRNvCCGxr9FFRLBC7NoTw-T8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
